server:
  port: 8761
  address: 10.20.5.146
eureka:
  instance:
  #设置服务地址
    hostname: ${server.address}
    prefer-ip-address: true
    instance-id: ${server.address}:${server.port}
  client:
  #设置不需要去检索服务（如果是集群，就需要修改为true）
    registerWithEureka: true
  #设置自己不注册自己（如果是集群，就需要修改为true）
    fetchRegistry: true
  #访问服务的url地址
    serviceUrl:
      defaultZone: http://${server.address}:8751/eureka/
#设置应用名称
spring:
  application:
    name: eurka-server

