server:
  port: 8751

eureka:
  instance:
  #设置服务地址
    hostname: 127.0.0.1
  client:
  #设置不需要去检索服务
    registerWithEureka: true
  #设置自己不注册自己
    fetchRegistry: true
  #访问服务的url地址
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#设置应用名称
spring:
  application:
    name: eurka-server

