spring:
  datasource:
    url: jdbc:mysql://10.20.4.226:3306/jwttsst?useUnicode=true&amp;autoReconnect=true&amp;characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: cjc1234
    tomcat:
      max-active: 20
      initial-size: 1
      max-wait: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9999

